### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by catb0t** [catb0t/exercism.factor#4]
# autogen:
- [ ] read / write config.json
- [ ] add custom key support
- [ ] tests!
- [ ] doc?
- [ ] allow GET local files
- [ ] use `unparse` not `present` (factor/factor#1834)
# self-update:
- [ ] prefer git pull
- [ ] tests!
- [ ] doc?
# config:
- [ ] rewrite json reading
- [ ] add write-out support
- [ ] tests!
- [ ] doc?
- [ ] update json struct to match actual used keys 
# testing:
- [ ] tests!
- [x] move config stuff to config-json
